#ifndef HANDWRITELIBRARY_GLOBAL_H
#define HANDWRITELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HANDWRITELIBRARY_LIBRARY)
#  define HANDWRITELIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HANDWRITELIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HANDWRITELIBRARY_GLOBAL_H
